### ISSUE TITLE
Is there a way to use queue to read data?

### ISSUE THREAD

**Issue by q1anzhen** [deepsphere/DeepSphere#35]
Hi, thanks for developing this great tool. It seems to be a good way to deal with spherical data.
Now, i am trying to implement this package in my work and i basically realized the training a model using the demo method.
I noticed that in the deme method, all the data will be read into the memory before training. But when I use a larger data set, it will inevitably have some insufficient memory problems.
I am wondering if you have designed an interface that uses queue data, like reading data from some TFRecord files and using a iterator something. That seems to be used in many deep learning project with TensorFlow.
Or do you have other ways to read larger datasets? Could you give me some hints?

Thanks a lot. :)

**Comment by mdeff** [comment]
Thanks for your kind words. We indeed always read from memory (because our machine had enough for our data) in our experiments. The easiest way if you already have a codebase is maybe to only reuse the NN layers and graph creation. Otherwise, if you can use PyTorch instead, [our implementation has a dataloader that will lazily load batches when needed](https://github.com/deepsphere/deepsphere-pytorch/blob/master/deepsphere/data/datasets/dataset.py).

**Comment by q1anzhen** [comment]
> Thanks for your kind words. We indeed always read from memory (because our machine had enough for our data) in our experiments. The easiest way if you already have a codebase is maybe to only reuse the NN layers and graph creation. Otherwise, if you can use PyTorch instead, [our implementation has a dataloader that will lazily load batches when needed](https://github.com/deepsphere/deepsphere-pytorch/blob/master/deepsphere/data/datasets/dataset.py).

thx, i will look into it!
:)
